module.exports = {
  content: [
    "./src/**/*.{html,ts}"
  ],
  theme: {
    extend: {
      colors: {
        "primary":                    "#006c49",
        "on-primary":                 "#ffffff",
        "primary-container":          "#10b981",
        "on-primary-container":       "#00422b",
        "primary-fixed":              "#6ffbbe",
        "primary-fixed-dim":          "#4edea3",
        "on-primary-fixed":           "#002113",
        "on-primary-fixed-variant":   "#005236",
        "secondary":                  "#565e74",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#dae2fd",
        "on-secondary-container":     "#5c647a",
        "secondary-fixed":            "#dae2fd",
        "secondary-fixed-dim":        "#bec6e0",
        "on-secondary-fixed":         "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary":                   "#55615a",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#99a69e",
        "on-tertiary-container":      "#303c36",
        "tertiary-fixed":             "#d9e6dd",
        "tertiary-fixed-dim":         "#bdcac1",
        "on-tertiary-fixed":          "#131e19",
        "on-tertiary-fixed-variant":  "#3e4943",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "background":                 "#f8f9ff",
        "on-background":              "#0b1c30",
        "surface":                    "#f8f9ff",
        "on-surface":                 "#0b1c30",
        "surface-variant":            "#d3e4fe",
        "on-surface-variant":         "#3c4a42",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#eff4ff",
        "surface-container":          "#e5eeff",
        "surface-container-high":     "#dce9ff",
        "surface-container-highest":  "#d3e4fe",
        "surface-dim":                "#cbdbf5",
        "surface-bright":             "#f8f9ff",
        "surface-tint":               "#006c49",
        "outline":                    "#6c7a71",
        "outline-variant":            "#bbcabf",
        "inverse-surface":            "#213145",
        "inverse-on-surface":         "#eaf1ff",
        "inverse-primary":            "#4edea3",
      },
      spacing: {
        "margin-mobile":  "16px",
        "container-max":  "1280px",
        "gutter":         "24px",
        "unit":           "4px",
        "stack-sm":       "8px",
        "stack-md":       "24px",
        "stack-lg":       "48px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg":     ["Inter", "sans-serif"],
        "body-md":     ["Inter", "sans-serif"],
        "body-sm":     ["Inter", "sans-serif"],
        "label-md":    ["Inter", "sans-serif"],
        "label-sm":    ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2",  letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3",  fontWeight: "600" }],
        "body-lg":     ["18px", { lineHeight: "1.6",  fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "1.5",  fontWeight: "400" }],
        "body-sm":     ["14px", { lineHeight: "1.5",  fontWeight: "400" }],
        "label-md":    ["14px", { lineHeight: "1.4",  letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm":    ["12px", { lineHeight: "1.2",  fontWeight: "600" }],
      },
      boxShadow: {
        "level-1": "0 4px 20px 0 rgba(15, 23, 42, 0.05)",
        "level-2": "0 10px 30px 0 rgba(15, 23, 42, 0.08)",
      },
    },
  },
  plugins: [],
}
